DISTANCE_STEP = 8

FORWARD = 1
REVERSE = 0

RIGHT = 0
LEFT = 1
FRONT = 2
BACK = 3

# Pin allocation
RIGHT_MOTOR_PWM     = 12
RIGHT_MOTOR_DIR     = 13
RIGHT_MOTOR_PULSE_A = 16
RIGHT_MOTOR_PULSE_B = 17
LEFT_MOTOR_PWM      = 19
LEFT_MOTOR_DIR      = 18
LEFT_MOTOR_PULSE_A  = 14
LEFT_MOTOR_PULSE_B  = 15

# Initial starting calibration
DEFAULT_TARGET_CLICKS = 2000
DEFAULT_SPEED_DUTY = 32000 

# Robot port
WEB_PORT = 8080

# Log size
LOG_BUFFER_SIZE = 1204
